### ISSUE TITLE
Request timestamp in results

### ISSUE THREAD

**Issue by betorcs** [jitcoder/es-query#1]
_First of all i'd like to say this plugin is great, thank you so much._

It'd be great if in query results add timestamp, because results of some  queries are the same.

**For example:**

- Requests

```
PUT /sample
```
```json
PUT /sample/_mapping/type1
{    
    "properties": {
        "name": { "type": "string" }
    }
}

```

- Result
```json
{
  "acknowledged": true
}
```

Expected something like.
```json
2017-02-06 15:03:34
{
  "acknowledged": true
}
```

**Comment by jitcoder** [comment]
I think thats a great idea, in fact now that I think about it, this is something thats been bothering me haha. I'll go ahead and add it soon. thank you for your feedback

**Comment by jitcoder** [comment]
https://github.com/jitcoder/es-query/pull/2

v0.0.5 published
