### ISSUE TITLE
Escaping query string values

### ISSUE THREAD

**Issue by luckybroman5** [jitcoder/es-query#3]
Example:
articles/default/_search?size=1

Returns an error when it is a valid request.

Probably due to escaping the query param as part of the path.

**Comment by betorcs** [comment]
Additional information.

The Following request:
`get edirectoryx/_search?pretty=true`

is returning
```json
[Query Information]

Requested Time  2/16/2017, 8:56:31 AM
Time Taken      5ms


[Response]

{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "No feature for name [_search?pretty=true]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "No feature for name [_search?pretty=true]"
  },
  "status": 400
}
```

**Comment by jitcoder** [comment]
got'cha, thanks will fix soon

**Comment by jitcoder** [comment]
fix for this is in progress

**Comment by diegomosela** [comment]
@jitcoder What's new about this? Can I help with something?

**Comment by jitcoder** [comment]
sorry got busy, I'll create a patch by today/tomorrow. sorry about that! @diegomosela

**Comment by diegomosela** [comment]
Good!

Tks

**Comment by jitcoder** [comment]
hello, please note this project has been abandoned in favor of https://marketplace.visualstudio.com/items?itemName=ria.elastic
