### ISSUE TITLE
Multiple Hosts Environment

### ISSUE THREAD

**Issue by shahidmau** [jitcoder/es-query#4]
Is there any way to put multiple hosts? That will be helpful to work with **multiple environments**.

**Example :**

Production : ip address of the production
Staging : ip address of the staging
XYZ : ip address of the xyz

Once hosts are saved like this then we should be able to switch environment any time.

It is very useful requirement because programmer like me works with multiple environments at the same time.

**Comment by jitcoder** [comment]
yes this sounds like a great feature. I've started working on this. Will update soon

**Comment by jitcoder** [comment]
hello, please note this project has been abandoned in favor of https://marketplace.visualstudio.com/items?itemName=ria.elastic
