### ISSUE TITLE
Stopping Execute Query

### ISSUE THREAD

**Issue by shahidmau** [jitcoder/es-query#5]
Is there any way to stop the executed query?

Sometime response does not come and it waits for response forever.
I face this issue frequently specially when my internet is disconnected between the execution of the query since I have a poor internet connection here.

**Comment by jitcoder** [comment]
this might be a little tricky but I will take a look in to it.
There might not be a way to abort a connection.
Ideally I would have the extension attempt to abort an existing request if another request comes in, as well as add a command for aborting a query.

**Comment by jitcoder** [comment]
hello, please note this project has been abandoned in favor of https://marketplace.visualstudio.com/items?itemName=ria.elastic
