### ISSUE TITLE
Content-Type Header enforced starting with ES version 6.x

### ISSUE THREAD

**Issue by 111andre111** [jitcoder/es-query#8]
Hi, short question.
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_rest_changes.html#_content_type_auto_detection
Starting with this version a Header
`Content-Type: application/json`
is needed for requests like a POST or a PUT. So the execution at the moment does not work.

Could this be fixed please or is this extension not maintained any more?

The response I get at the moment is this:
```
{
  "error": "Content-Type header [] is not supported",
  "status": 406
}

```

**Comment by jitcoder** [comment]
Heya. Im no longer maintaining this extension, I highly recommend the extension in the readme. A few months after I first released this extension, someone authored a much much better one so I deprecated this one in favor of it. Check out the readme ;)

**Comment by 111andre111** [comment]
Ok, sorry for that, was not aware of that.
